services:
  dev:
    # other definitions
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached